// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('About', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('About', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1034, height: 666 })
    await driver.findElement(By.linkText("About")).click()
    await driver.findElement(By.css(".font-medium:nth-child(2)")).click()
    await driver.findElement(By.linkText("Contact")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("John Doe")
    await driver.findElement(By.id("email")).sendKeys("tempemail@abc.com")
    await driver.findElement(By.id("subject")).sendKeys("Product Pricing Query")
    await driver.findElement(By.id("message")).sendKeys("I want to buy the platform for my university students")
    await driver.findElement(By.css(".bg-white")).click()
    {
      const element = await driver.findElement(By.css(".bg-white"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".lucide-linkedin")).click()
    vars["win9166"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win9166"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
  })
})
