// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('NavBar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('NavBar', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css(".gap-3:nth-child(1) > span")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > span")).click()
    await driver.findElement(By.css(".gap-3:nth-child(1) > span")).click()
    await driver.findElement(By.css(".gap-3:nth-child(3) > span")).click()
    await driver.findElement(By.css(".flex:nth-child(4) > span")).click()
    await driver.findElement(By.linkText("Generator")).click()
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("MERN")
    await driver.findElement(By.name("search")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".w-full:nth-child(2) > .truncate")).click()
    await driver.findElement(By.css("div:nth-child(1) > .space-y-2 .truncate")).click()
  })
})
