// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('NavBar_Search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('NavBar_Search', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("C++")
    await driver.findElement(By.name("search")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".rounded-xl")).click()
    await driver.findElement(By.css(".rounded-xl")).click()
    {
      const element = await driver.findElement(By.css(".rounded-xl"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".rounded-xl")).click()
    await driver.findElement(By.css(".rounded-xl")).sendKeys("MERN")
    await driver.findElement(By.css(".rounded-xl")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".rounded-xl")).sendKeys("AI")
    await driver.findElement(By.css(".rounded-xl")).sendKeys(Key.ENTER)
    await driver.close()
  })
})
