// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Navbar_Account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Navbar_Account', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css(".gap-3 > span:nth-child(2)")).click()
    await driver.findElement(By.css(".inline-flex")).click()
    await driver.findElement(By.css(".flex-col > .px-4")).click()
    await driver.findElement(By.css(".lucide-x")).click()
    await driver.findElement(By.css(".bg-slate-800")).click()
    await driver.findElement(By.css(".lucide-x")).click()
    await driver.findElement(By.css(".h-8:nth-child(30)")).click()
    await driver.findElement(By.css(".py-1")).click()
    await driver.findElement(By.css(".bg-red-600")).click()
    await driver.findElement(By.css(".transition-colors:nth-child(2)")).click()
  })
})
