// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('About', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('About', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1034, height: 666 })
    await driver.findElement(By.linkText("About")).click()
    await driver.findElement(By.css(".font-medium:nth-child(2)")).click()
  })
})
