// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RoadmapPage_IDE', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('RoadmapPage_IDE', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css(".space-y-8")).click()
    await driver.findElement(By.linkText("Roadmaps")).click()
    await driver.findElement(By.linkText("Learn")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("#chapter-1 .p-2:nth-child(1) > .lucide")).click()
    vars["win7679"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win7679"])
    await driver.findElement(By.css(".view-lines")).click()
    await driver.findElement(By.css(".view-lines")).click()
    await driver.findElement(By.css(".inputarea")).sendKeys("console.log(\"HEllo\")")
    await driver.findElement(By.css(".bg-gray-900:nth-child(3)")).click()
    await driver.findElement(By.css(".lucide-file-plus")).click()
    await driver.findElement(By.css(".placeholder-gray-500")).sendKeys("hello.js")
    await driver.findElement(By.css(".placeholder-gray-500")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".bg-blue-600")).click()
    await driver.switchTo().window(vars["root"])
    await driver.close()
    await driver.switchTo().window(vars["win7679"])
    await driver.findElement(By.css(".bg-gray-900 > span")).click()
    await driver.findElement(By.css("circle:nth-child(1)")).click()
    await driver.findElement(By.css(".lucide-moon")).click()
    {
      const element = await driver.findElement(By.css("circle:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".lucide-menu")).click()
    await driver.findElement(By.css(".lucide-menu")).click()
    await driver.findElement(By.css(".resize-none")).click()
    await driver.findElement(By.css(".bg-gray-900:nth-child(3)")).click()
    await driver.findElement(By.css(".font-medium")).click()
    await driver.findElement(By.css(".disabled\\3Aopacity-50")).click()
  })
})
