// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RoadmapPage', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('RoadmapPage', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css(".flex:nth-child(4) > span")).click()
    await driver.findElement(By.css(".mt-auto > button")).click()
    await driver.findElement(By.css(".bg-blue-600:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".bg-blue-600:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".bg-blue-600 > .text-xs")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .bg-slate-700")).click()
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("6")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("7")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".px-2:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("8")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("9")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".to-purple-900\\/30")).click()
    {
      const element = await driver.findElement(By.css(".to-purple-900\\/30"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("8")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("7")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".px-2:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("6")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("5")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".px-2:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("4")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("3")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".px-2:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("1")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("0")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".px-2:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".flex-1:nth-child(3)")).sendKeys("1")
    await driver.findElement(By.css(".flex-1:nth-child(3)")).click()
    await driver.findElement(By.css(".flex-1:nth-child(3)")).sendKeys("2")
    await driver.findElement(By.css(".flex-1:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".flex-1:nth-child(3)")).sendKeys("1")
    await driver.findElement(By.css(".flex-1:nth-child(3)")).click()
    await driver.findElement(By.css(".flex-1:nth-child(3)")).sendKeys("0")
    await driver.findElement(By.css(".flex-1:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".px-2:nth-child(1)")).sendKeys("1")
    await driver.findElement(By.css(".px-2:nth-child(1)")).click()
    await driver.findElement(By.css(".bg-purple-600")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("#chapter-1 .flex > .lucide")).click()
    await driver.findElement(By.css("div:nth-child(1) > .bg-gradient-to-br > .flex > .lucide > path")).click()
    await driver.findElement(By.css(".whitespace-nowrap:nth-child(1)")).click()
    await driver.findElement(By.css(".disabled\\3A cursor-not-allowed")).click()
    {
      const element = await driver.findElement(By.css(".disabled\\3A cursor-not-allowed"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".lucide-x")).click()
    await driver.findElement(By.css(".whitespace-nowrap:nth-child(2)")).click()
    await driver.findElement(By.css(".lucide-x")).click()
    await driver.findElement(By.css(".px-4:nth-child(3)")).click()
    await driver.findElement(By.css(".hover\\3A bg-slate-700:nth-child(2)")).click()
    await driver.findElement(By.css(".px-4:nth-child(4)")).click()
    await driver.findElement(By.css(".hover\\3A bg-slate-700:nth-child(2)")).click()
    await driver.findElement(By.css(".px-4:nth-child(5)")).click()
    await driver.findElement(By.css(".hover\\3Atext-slate-300")).click()
    await driver.findElement(By.css(".hover\\3Atext-slate-300")).click()
    await driver.findElement(By.css(".disabled\\3A cursor-not-allowed")).click()
    {
      const element = await driver.findElement(By.css(".disabled\\3A cursor-not-allowed"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".hover\\3Atext-slate-300")).click()
    await driver.findElement(By.css(".p-4:nth-child(1) > .space-y-2 > .flex:nth-child(1)")).click()
    await driver.findElement(By.css(".p-4:nth-child(1) > .px-3")).click()
    await driver.findElement(By.css(".lucide-x")).click()
  })
})
