// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RoadmapPage_Chat', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('RoadmapPage_Chat', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css(".flex:nth-child(4) > span")).click()
    await driver.findElement(By.linkText("Learn")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("#chapter-1 .p-2:nth-child(2)")).click()
    vars["win2027"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win2027"])
    await driver.findElement(By.css(".bg-transparent")).click()
  })
})
