// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SignIn_Using_Email', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SignIn_Using_Email', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1034, height: 666 })
    await driver.findElement(By.linkText("Get Started")).click()
    {
      const element = await driver.findElement(By.css(".lucide-menu > path:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".lucide-menu > path:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".lucide-menu > path:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".lucide-menu")).click()
    {
      const element = await driver.findElement(By.css(".lucide-menu > path:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".lucide-x")).click()
    await driver.findElement(By.css(".lucide-menu > path:nth-child(2)")).click()
    await driver.executeScript("window.scrollTo(0,562.4000244140625)")
    await driver.findElement(By.css(".relative:nth-child(4) > .cursor-pointer")).click()
    await driver.findElement(By.css(".relative:nth-child(4) > .cursor-pointer")).click()
    await driver.findElement(By.css(".relative:nth-child(4) > .cursor-pointer")).click()
    await driver.findElement(By.css(".w-full > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("nikhatandray@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Abc@123")
    await driver.findElement(By.css(".disabled\\3Aopacity-50")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Abc@1234")
    await driver.findElement(By.css(".disabled\\3Aopacity-50")).click()
    await driver.findElement(By.css(".lucide-eye")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Abc@123")
    await driver.findElement(By.css(".disabled\\3Aopacity-50")).click()
    {
      const element = await driver.findElement(By.css(".disabled\\3Aopacity-50"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Abc@12345")
    await driver.findElement(By.css(".disabled\\3Aopacity-50")).click()
    {
      const element = await driver.findElement(By.css(".disabled\\3Aopacity-50"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
