// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('HomePage_v2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HomePage_v2', async function() {
    // Test name: HomePage_v2
    // Step # | name | target | value
    // 1 | open | https://coding-learning-zeta.vercel.app/ | 
    await driver.get("https://coding-learning-zeta.vercel.app/")
    // 2 | setWindowSize | 1550x830 | 
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    // 3 | mouseOver | css=.mr-8 > .text-white | 
    {
      const element = await driver.findElement(By.css(".mr-8 > .text-white"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | click | css=.flex:nth-child(5) > span | 
    await driver.findElement(By.css(".flex:nth-child(5) > span")).click()
    // 5 | click | css=.bg-slate-800\/30 > span | 
    await driver.findElement(By.css(".bg-slate-800\\/30 > span")).click()
    // 6 | click | css=.gap-3:nth-child(1) > span | 
    await driver.findElement(By.css(".gap-3:nth-child(1) > span")).click()
    // 7 | click | linkText=Features | 
    await driver.findElement(By.linkText("Features")).click()
    // 8 | click | linkText=Pricing | 
    await driver.findElement(By.linkText("Pricing")).click()
    // 9 | click | linkText=FAQ | 
    await driver.findElement(By.linkText("FAQ")).click()
    // 10 | click | linkText=About | 
    await driver.findElement(By.linkText("About")).click()
    // 11 | click | linkText=Contact | 
    await driver.findElement(By.linkText("Contact")).click()
    // 12 | click | linkText=Privacy | 
    await driver.findElement(By.linkText("Privacy")).click()
    // 13 | click | linkText=Terms | 
    await driver.findElement(By.linkText("Terms")).click()
    // 14 | click | linkText=Privacy | 
    await driver.findElement(By.linkText("Privacy")).click()
  })
})
