// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('roadmap', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('roadmap', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css(".flex:nth-child(4) > span")).click()
    await driver.findElement(By.css(".group:nth-child(1) .lucide")).click()
    {
      const element = await driver.findElement(By.css(".lucide-pin > path:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".py-4")).click()
    await driver.findElement(By.css(".group:nth-child(1) > .absolute:nth-child(2) > svg")).click()
    await driver.findElement(By.css(".py-2:nth-child(2)")).click()
    await driver.findElement(By.css(".lucide-pin-off")).click()
    await driver.findElement(By.linkText("Learn")).click()
  })
})
