// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SIgnup_using_OAuth', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SIgnup_using_OAuth', async function() {
    await driver.get("https://coding-learning-zeta.vercel.app/")
    await driver.manage().window().setRect({ width: 1034, height: 666 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.linkText("Sign up")).click()
    await driver.findElement(By.css(".w-full:nth-child(4)")).click()
    await driver.findElement(By.css(".ObDc3")).click()
    await driver.findElement(By.id("identifierId")).click()
    await driver.findElement(By.css(".zIgDIc")).click()
    await driver.findElement(By.id("identifierId")).click()
    await driver.findElement(By.id("identifierId")).click()
    await driver.findElement(By.id("identifierId")).sendKeys("202301135@dau.ac.in")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.findElement(By.name("Passwd")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("asdasdasd")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("aasdasdasdasd")
    await driver.findElement(By.name("Passwd")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click()
  })
})
